### ISSUE TITLE
Pas de message sur register ou de redirection après enregistrement

### ISSUE THREAD

**Issue by automatedb** [FrancoisDoussin/tp_node#12]

**Comment by automatedb** [comment]
Server is listening on port 8080
events.js:163
      throw er; // Unhandled 'error' event
      ^

Error: Can't set headers after they are sent.
    at ServerResponse.setHeader (_http_outgoing.js:371:11)
    at ServerResponse.header (/home/nickleus/Documents/Developments/Cours/DL18-TP/tp_node/node_modules/express/lib/response.js:725:10)
    at ServerResponse.location (/home/nickleus/Documents/Developments/Cours/DL18-TP/tp_node/node_modules/express/lib/response.js:842:15)
    at ServerResponse.redirect (/home/nickleus/Documents/Developments/Cours/DL18-TP/tp_node/node_modules/express/lib/response.js:880:18)
    at /home/nickleus/Documents/Developments/Cours/DL18-TP/tp_node/app/controllers/AuthCtrl.js:84:29
    at /home/nickleus/Documents/Developments/Cours/DL18-TP/tp_node/node_modules/mongoose/lib/model.js:3701:16
    at /home/nickleus/Documents/Developments/Cours/DL18-TP/tp_node/node_modules/mongoose/lib/services/model/applyHooks.js:146:20
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)

npm ERR! Linux 4.8.0-45-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v7.8.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tptoutcourt@1.0.0 start: `node app/index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the tptoutcourt@1.0.0 start script 'node app/index.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the tptoutcourt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node app/index.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs tptoutcourt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls tptoutcourt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/nickleus/.npm/_logs/2017-04-05T07_42_02_536Z-debug.log
